- name: Prepare-host
  hosts: new
  become: true
  vars:
    username: bomzheg
  tasks:
    - name: Install ansible requirements
      ansible.builtin.apt:
        name: python3-apt
        update_cache: true
    - name: Setup passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present
    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        groups: [sudo, docker]
        shell: /bin/bash
        append: true
        create_home: true
    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/ychebyshev.pub') }}"
    - name: Install all soft
      ansible.builtin.apt:
        pkg:
          - curl
          - vim
          - git
          - tmux
          - htop
    - name: Configure hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Configure hosts file
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        state: present
        regexp: "^{{ ansible_host }} "
        line: "{{ ansible_host }} {{ hostname }}"

    - name: Allow output
      ansible.builtin.iptables:
        chain: OUTPUT
        jump: ACCEPT
      become: true

    - name: Allow ssh and https
      ansible.builtin.iptables:
        chain: INPUT
        destination_ports:
          - "22"
          - "80"
          - "443"
        protocol: tcp
        jump: ACCEPT
      become: true

    - name: Allow established
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Allow lo
      ansible.builtin.iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Block any other ports
      ansible.builtin.iptables:
        chain: INPUT
        jump: DROP
      become: true
