collections:
  - name: victoriametrics.cluster
    version: 0.45.0
  - name: prometheus.prometheus
    version: 0.12.0
roles:
  - name: 0x0i.grafana
    version: v0.1.0
  - name: ome.cadvisor
    version: 0.5.0
