- name: Syncthing
  hosts: prepared
  tasks:
    - name: Add key for Syncthing repo
      ansible.builtin.apt_key:
        url: https://syncthing.net/release-key.gpg
        state: present
      become: true

    - name: Add Syncthing repo to sources list
      ansible.builtin.apt_repository:
        repo: 'deb https://apt.syncthing.net/ syncthing stable'
        state: present
      become: true

    - name: Install Syncthing
      ansible.builtin.apt:
        name: syncthing
        update_cache: true
      become: true

    - name: Create systemd service for Syncthing (if needed)
      ansible.builtin.copy:
        dest: /etc/systemd/system/syncthing@.service
        mode: "644"
        content: |
          [Unit]
          Description=Syncthing - Open Source Continuous File Synchronization for %I
          Documentation=man:syncthing(1)
          After=network.target

          [Service]
          User={{ ansible_user_id }}
          Group={{ ansible_user_id }}
          WorkingDirectory=/home/{{ ansible_user_id }}/syncthing
          ExecStart=/usr/bin/syncthing serve --no-browser --no-restart --logflags=0
          Restart=on-failure
          SuccessExitStatus=3 4
          RestartForceExitStatus=3 4

          [Install]
          WantedBy=multi-user.target
      become: true
      notify: Reload systemd daemon

    - name: Run Syncthing
      ansible.builtin.service:
        name: syncthing@{{ ansible_user_id }}
        state: started
        enabled: true
      become: true

  handlers:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
      become: true
